/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Account: typeof import('./src/views/login/LoginType/account.vue')['default']
    App: typeof import('./src/App.vue')['default']
    AppMain: typeof import('./src/layout/AppMain.vue')['default']
    Banner: typeof import('./src/views/home/components/banner.vue')['default']
    Bre: typeof import('./src/components/bre/index.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb/index.vue')['default']
    Communicate: typeof import('./src/views/usedCar/detail/components/communicate.vue')['default']
    Detail: typeof import('./src/views/usedCar/detail/index.vue')['default']
    DetailSwiper: typeof import('./src/views/usedCar/detail/components/detailSwiper.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    Footer: typeof import('./src/layout/Footer/index.vue')['default']
    Header: typeof import('./src/layout/Header/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/views/home/index.vue')['default']
    Hotel: typeof import('./src/views/hotel/index.vue')['default']
    Layout: typeof import('./src/layout/index.vue')['default']
    Login: typeof import('./src/views/login/index.vue')['default']
    Product: typeof import('./src/views/product/index.vue')['default']
    Quality: typeof import('./src/views/quality/index.vue')['default']
    Rec: typeof import('./src/views/usedCar/rec/index.vue')['default']
    recommend: typeof import('./src/views/UsedCar/components/ recommend.vue')['default']
    Recommend: typeof import('./src/views/UsedCar/components/ Recommend.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/views/usedCar/search/index.vue')['default']
    SearchBar: typeof import('./src/components/SearchBar/index.vue')['default']
    SearchCar: typeof import('./src/views/UsedCar/Search/SearchCar.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    UsedCar: typeof import('./src/views/usedCar/index.vue')['default']
    Verify: typeof import('./src/views/login/LoginType/verify.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
